#!/usr/bin/env bash
set -euo pipefail

# SOC Quickstart installer
# Download this file and run it similarly to the Wazuh quickstart.
# Example:
#   curl -fsSLO https://raw.githubusercontent.com/practikalaus/soc/main/installer/soc-quickstart.sh && sudo bash ./soc-quickstart.sh -a

SOC_BRAND_TITLE_DEFAULT="Practikal IT Solutions | Security Operations & IT Audit Centre"
SOC_BRAND_TITLE="${SOC_BRAND_TITLE:-$SOC_BRAND_TITLE_DEFAULT}"
SOC_MAJOR_DEFAULT="4.14"
SOC_MAJOR="${SOC_MAJOR:-$SOC_MAJOR_DEFAULT}"

usage() {
  cat <<EOF
SOC quickstart installer.

Usage:
  soc-quickstart.sh [--major ${SOC_MAJOR_DEFAULT}] [--] <soc-install.sh args>

Examples:
  # All-in-one (single node)
  sudo bash ./soc-quickstart.sh -a

  # Pin a specific major stream
  sudo bash ./soc-quickstart.sh --major 4.14 -a

Notes:
- This script downloads the upstream Wazuh installation assistant (baseline) and generates a branded installer named ./soc-install.sh.
- The generated bundle file is named soc-install-files.tar (not wazuh-install-files.tar).
- Underlying packages/services/paths remain the upstream names for compatibility.
EOF
}

major="$SOC_MAJOR"

# Parse our flags, then forward the rest to soc-install.sh
forward_args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --major)
      major="${2:-}"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    --)
      shift; forward_args+=("$@"); break ;;
    *)
      forward_args+=("$1"); shift ;;
  esac
done

if [[ ${#forward_args[@]} -eq 0 ]]; then
  echo "Missing installer arguments (example: -a)." >&2
  usage
  exit 2
fi

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

need_cmd curl
need_cmd python3
need_cmd bash

workdir="$(mktemp -d -t soc-installer-XXXXXX)"
cleanup() { rm -rf "$workdir"; }
trap cleanup EXIT

up_base="https://packages.wazuh.com/${major}"

printf '%s\n' "${SOC_BRAND_TITLE}: downloading upstream baseline (${major})..."

curl -fsSLo "${workdir}/wazuh-install.sh" "${up_base}/wazuh-install.sh"

# Keep config.yml alongside the generated installer for users that later do distributed installs.
curl -fsSLo "${workdir}/config.yml" "${up_base}/config.yml"

IN_FILE="${workdir}/wazuh-install.sh" OUT_FILE="${workdir}/soc-install.sh" SOC_BRAND_TITLE="${SOC_BRAND_TITLE}" \
python3 - <<'PY'
import os

in_file = os.environ["IN_FILE"]
out_file = os.environ["OUT_FILE"]
brand_title = os.environ.get("SOC_BRAND_TITLE", "").strip()

with open(in_file, "r", encoding="utf-8", errors="replace") as f:
    src = f.read()

# Tar/log naming
src = src.replace('readonly tar_file_name="wazuh-install-files.tar"',
                  'readonly tar_file_name="soc-install-files.tar"')
src = src.replace(
  'readonly logfile="/var/log/wazuh-install.log"',
  'logfile="/tmp/soc-install-${UID}.log"\nif [ "${EUID}" -eq 0 ]; then\n  logfile="/var/log/soc-install.log"\nfi\nreadonly logfile'
)

# Help text references
src = src.replace('wazuh-install-files.tar', 'soc-install-files.tar')

# Brand --version / startup labels (keep actual version values)
src = src.replace('common_logger "Wazuh version: ${wazuh_version}"',
                  'common_logger "SOC baseline (Wazuh) version: ${wazuh_version}"')
src = src.replace('common_logger "Wazuh installation assistant version: ${wazuh_install_vesion}"',
                  'common_logger "SOC installer version: ${wazuh_install_vesion}"')
src = src.replace('common_logger "Starting Wazuh installation assistant. Wazuh version:',
                  'common_logger "Starting SOC installer. SOC baseline (Wazuh) version:')

# Add a banner line once (best-effort)
needle = 'common_logger "Verbose logging redirected to ${logfile}"'
if needle in src and brand_title:
    insertion = needle + "\n    common_logger \"" + brand_title.replace('"', '\\"') + "\""
    src = src.replace(needle, insertion, 1)

header = (
    "# --- SOC wrapper note ---\n"
    "# Generated by soc-quickstart.sh from upstream baseline.\n"
    "# Branding applied (tar/log filenames, banner text).\n"
    "# ---\n\n"
)

if src.startswith('#!/bin/bash'):
    src = '#!/bin/bash\n\n' + header + src[len('#!/bin/bash\n\n'):]
elif src.startswith('#!/usr/bin/env bash'):
    src = '#!/usr/bin/env bash\n\n' + header + src[len('#!/usr/bin/env bash\n\n'):]
else:
    src = header + src

with open(out_file, "w", encoding="utf-8") as f:
    f.write(src)
PY

chmod 0755 "${workdir}/soc-install.sh"

# Materialize into current directory (matches Wazuh quickstart style)
cp -f "${workdir}/soc-install.sh" ./soc-install.sh
cp -f "${workdir}/config.yml" ./config.yml
chmod 0755 ./soc-install.sh

printf '%s\n' "${SOC_BRAND_TITLE}: running SOC installer (./soc-install.sh ${forward_args[*]})"

# Execute upstream logic with your args
bash ./soc-install.sh "${forward_args[@]}"

# Create SOC systemd service aliases (so operators can use soc-* names)
if [[ "${EUID}" -eq 0 ]] && command -v systemctl >/dev/null 2>&1; then
  unit_dir="/etc/systemd/system"
  mkdir -p "${unit_dir}"

  link_alias() {
    local alias_unit="$1"   # soc-indexer.service
    local target_unit="$2"  # wazuh-indexer.service

    local target_path=""
    target_path="$(systemctl show -p FragmentPath "${target_unit}" --no-pager 2>/dev/null | sed 's/^FragmentPath=//')"
    if [[ -n "${target_path}" && -f "${target_path}" ]]; then
      ln -sf "${target_path}" "${unit_dir}/${alias_unit}"
    fi
  }

  link_alias soc-indexer.service wazuh-indexer.service
  link_alias soc-manager.service wazuh-manager.service
  link_alias soc-dashboard.service wazuh-dashboard.service
  systemctl daemon-reload

  printf '%s\n' "${SOC_BRAND_TITLE}: SOC service aliases installed (soc-indexer, soc-manager, soc-dashboard)"
fi
